Added JSON importer/exporter for SecurityAnalysisResult
itesla/ipst-core pull request #72
Opened 2017-03-06 15:24 UTC by massimo-ferraro

2017-03-07 17:02 UTC, mathbagu requested changes

2017-03-07 17:02 UTC, mathbagu commented on pom.xml
> +        <jackson.version>2.7.3</jackson.version>
You should use the current version of jackson is 2.8.7

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/pom.xml
>              <groupId>eu.itesla_project</groupId>
Could you please fix the groupid: replace eu.itesla_project by ${project.groupId} for all ipst-core dependencies in this module

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/pom.xml
> +            <groupId>eu.itesla_project</groupId>
See previous remark

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/src/main/java/eu/itesla_project/security/json/ContingencyDeserializer.java
> +public class ContingencyDeserializer extends StdDeserializer<Contingency> {
This class should be moved to the contingency-api module in a json subpackage: this serialization class could be reused in another context.

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/src/main/java/eu/itesla_project/security/json/ContingencyDeserializer.java
> +                    break;
I think a default statement should be added here.

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/src/main/java/eu/itesla_project/security/LimitViolation.java
> +    public LimitViolation(@JsonProperty("subject") Identifiable subject, @JsonProperty("limitType") LimitViolationType limitType,
LimitViolation should be independent of the network. Subject should be replaced by a subjectId parameter.

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/src/main/java/eu/itesla_project/security/json/IdentifiableDeserializer.java
> +public class IdentifiableDeserializer  extends StdDeserializer<Identifiable> {
This class will be removed after LimitViolation.subject replacement

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/src/main/java/eu/itesla_project/security/json/IdentifiableSerializer.java
> +public class IdentifiableSerializer  extends StdSerializer<Identifiable> {
This class will be removed after LimitViolation.subject replacement

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/src/main/java/eu/itesla_project/security/json/JsonConverter.java
> +    public static SecurityAnalysisResult importSecurityAnalysisResult(Reader reader, Network network) throws JsonParseException, JsonMappingException, IOException {
There is no need of a Network instance once the LimitViolation.subject replacement is done.

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/src/test/java/eu/itesla_project/security/json/JsonConverterTest.java
> +        Generator generator = network.getGenerator("GEN");
There is no need to create a full network to create a SecurityAnalysisResult once LimitViolation.subject replacement is done.

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/src/test/java/eu/itesla_project/security/json/JsonConverterTest.java
> +                     "\"country\":null,\"baseVoltage\":\"NaN\"}],\"actionsTaken\":[\"action1\",\"action2\"]}]}";
Could be stored in a test resource file to be easier to adapt in the future

2017-03-07 17:02 UTC, mathbagu commented on security-analysis/src/main/java/eu/itesla_project/security/SecurityAnalysisResult.java
> +    public SecurityAnalysisResult(@JsonProperty("preContingencyResult") PreContingencyResult preContingencyResult,
We have to add a version parameter to SecurityAnalysisResult export to be able, in the future, to manage several versions of this export.

2017-03-07 17:22 UTC, massimo-ferraro commented on pom.xml
> +        <jackson.version>2.7.3</jackson.version>
The version was chosen to be compatible with jackson version used in ipst

2017-03-07 17:24 UTC, mathbagu commented on pom.xml
> +        <jackson.version>2.7.3</jackson.version>
The version used by ipst should be adapt to be compatible with ipst-core. This adaptation should be done in ipst first.

2017-03-28 17:40 UTC, mathbagu commented on pom.xml
> +        <jackson.version>2.8.7</jackson.version>
Could you please open a new PR in IPST to upgrade Jackson too ?

2017-04-11 16:59 UTC, mathbagu approved these changes

2017-04-18 09:39 UTC, geofjamg requested changes

2017-04-18 09:39 UTC, geofjamg commented on security-analysis/src/test/java/eu/itesla_project/security/json/SecurityAnalysisResultJsonTest.java
> +        SecurityAnalysisResultSerializer.write(create(), Paths.get("/tmp/toto.json"));
Use in memory file system instead, to avoid relying on /tmp

2017-04-18 09:39 UTC, geofjamg commented on security-analysis/src/test/resources/SecurityAnalysisResult.json
> +{
Is is the right json file naming convention?

2017-04-18 18:38 UTC, geofjamg approved these changes

2017-04-19 07:02 UTC, merged